name: Laravel Tests

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15 # Use latest stable PostgreSQL version
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 🛠 Checkout Code
        uses: actions/checkout@v4

      - name: 📦 Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2 # Change this based on your Laravel version
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: ⚡ Install Composer Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install --prefer-dist --optimize-autoloader

      - name: 🔑 Set Up Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=testing" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=secret" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "APP_ENV=testing" >> .env

      - name: 🔄 Wait for PostgreSQL
        run: sleep 10 # Ensures PostgreSQL is ready before running migrations

      - name: 📊 Run Migrations
        run: php artisan migrate --env=testing --force

      - name: 🧪 Run Pest Tests
        run: vendor/bin/pest --colors
